### ISSUE TITLE
Filter by Language

### ISSUE THREAD

**Issue by melbasuonyy** [Ozencb/yts-scraper#1]
Thanks for the great work but I have suggestion if possible to categorized also by language from movie description

**Comment by ozencb** [comment]
YTS API does not support filtering by language, unfortunately. It does have a language key for every film but, as far as I have seen, every movie is listed as English so language key on API has no use 😔

**Comment by melbasuonyy** [comment]
yes I have noticed the same also in API but inside each movie the language is mentioned :( hope they fix that as many movies are not english 
your repo. is great but if it support IMDB contest code to be extracted will be perfect

**Comment by ozencb** [comment]
I am sorry, I don't know what an IMDB contest code is. Can you show me an example?

**Comment by melbasuonyy** [comment]
the IMDB number it's unique number for movie start with ttXXXXXX and it's available in API

**Comment by ozencb** [comment]
Added the option to append IMDb ID, as well as multiprocess support and an option to download movie posters. You can append IMDb ID by adding "-i" to arguments
