### ISSUE TITLE
How to download a single link ?

### ISSUE THREAD

**Issue by ItsPiyusha** [Ozencb/yts-scraper#13]
what should be the options for the yts-scrapper command so that a single movie link can be downloaded.

**Comment by ozencb** [comment]
Hello,

YTS-Scraper does not have this functionality, I am afraid. Scrapers are usually designed to find and download files in bulk. It is not designed to download a single link but let me ask you, what is preventing you from downloading the link directly from YTS?

**Comment by ItsPiyusha** [comment]
Hello,
Ok, should I close that issue then? I'm not really sure what is the exact
issue in downloading single movie link, but I think it's because the
torrents are banned in India.

**Comment by ozencb** [comment]
Yes, if you cannot access [YTS](https://yts.mx) directly then this tool simply will not work. I advise against using it if it's illegal to download torrent files in your country, so please make sure that it is okay to tinker with yts-scraper.

Please create a new issue if anything else comes up.

Have a nice day

**Comment by ItsPiyusha** [comment]
as your tool is working fine, maybe I can download the single movie or
series link too, can you tell me how to do that? Please!
Thank you! Have a nice day!!
