### ISSUE TITLE
Not Downloading any files

### ISSUE THREAD

**Issue by melbasuony** [Ozencb/yts-scraper#6]
Hi, 

I have an issue when i'm trying to download any file from page 170 - however page 160 is fetching some movies but not everything (stop after small amount of movies) (downloading not started

Directory:      ./None
Quality:        all
Movie Genre:    all
Minimum Rating: 0
Categorization: none
Minimum Year:   1999
Starting page:  170
Movie posters:  False
Append IMDb ID: True
Multiprocess:   True

Query was successful.
Found 7958 movies. Download starting...

Downloading:   0%|                                                                         | 0/7958 [00:00<?, ?Files/s]
Download finished.

option: If you can include an export option as CSV include (URL 72P - 1080P - 2160P ) + IMDB code instead of downloading all the files from CMD it can be exported as CSV as well

**Comment by melbasuony** [comment]
now language option is available but I think you stopped supporting the scraper :(

**Comment by ozencb** [comment]
Sorry for the late reply. I did try to reproduce this issue to no avail. I will try to implement an export CSV option when I have the time.

As for the language option; I did look into it but language info on the API is far from reliable. You can look for yourself and see that lots of non-English movies has English listed as their language. This option can easily be implemented but it won't do the job, so for now I have no intention of implementing it.

**Comment by melbasuony** [comment]
Thanks alot 
yes CSV will be more reliable when you have time you can do it 
for language i randomly checked before it looks most English titles are correct may be iam wrong but if it's easy to implement why not :)

**Comment by ozencb** [comment]
CSV support was added. See:

https://github.com/Ozencb/yts-scraper/commit/f014ba367d45ebfee880eea397a3b0d77a75024e
