### ISSUE TITLE
Program Crashes After %1 and throws KeyError: 'genres' among other things

### ISSUE THREAD

**Issue by Arefu** [Ozencb/yts-scraper#9]
> Downloading:   1%|▋                                                                                                          | 109/18389 [04:58<13:56:11,  2.74s/Files]Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/YTS_Scraper-0.1.1-py3.8.egg/yts_scraper/main.py", line 153, in main
>     scraper.download()
>   File "/usr/lib/python3.8/site-packages/YTS_Scraper-0.1.1-py3.8.egg/yts_scraper/scraper.py", line 355, in download
>     self.__initialize_download()
>   File "/usr/lib/python3.8/site-packages/YTS_Scraper-0.1.1-py3.8.egg/yts_scraper/scraper.py", line 202, in __initialize_download
>     self.__filter_torrents(movie)
>   File "/usr/lib/python3.8/site-packages/YTS_Scraper-0.1.1-py3.8.egg/yts_scraper/scraper.py", line 212, in __filter_torrents
>     movie_genres = movie['genres']
> KeyError: 'genres'
> Downloading:   1%|▋`

I am running it using `yts-scraper -q 1080p -o torrents`

Any idea?

**Comment by ozencb** [comment]
The `KeyError` means that one of the movies is lacking `genres` key data that's necessary for the program to run properly. It seems that YTS's API is not as uniform as I thought, so I should implement some sort of control to catch these cases. I will look into it 👍

**Comment by ozencb** [comment]
Should be working now.
7bcd2bc3eecb7f39ad9150a949d132fbbcfcefba

**Comment by Arefu** [comment]
Yeah, I had a feeling it was gonna be something like that lol, I went to add it myself, but yeah nah, python ain't my thing.
Cheers for the fast turn around :)
